# ALIASES
alias repos="cd /Users/tstachl/Workspace/personal/repos" # new macbook?
alias la="ls -la --color=auto"
alias rustup_install="curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"

# FUNCTIONS
devenv() {
  docker run --rm --privileged -ite REPO=$1 -e TERM=alacritty --mount source=devenv,target=/home/thomas/workspace -v /var/run/docker.sock:/var/run/docker.sock tstachl/devenv
}

