# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# config dir
if [ -f "${XDG_CONFIG_HOME}/bash/bash_variables" ]; then
  source "${XDG_CONFIG_HOME}/bash/bash_variables"
fi

if [ -f "${XDG_CONFIG_HOME}/bash/bash_prompt" ]; then
  source "${XDG_CONFIG_HOME}/bash/bash_prompt"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi
