# ALIASES
alias repos="cd /Users/tstachl/Workspace/personal/repos" # new macbook?
alias la="ls -la --color=auto"

# FUNCTIONS
devenv() {
  docker run --rm --privileged -ite REPO=$1 --mount source=devenv,target=/home/thomas/workspace -v /var/run/docker.sock:/var/run/docker.sock tstachl/devenv
}

