alias devenv="docker run --rm --privileged -ite REPO=$1 --mount source=devenv,target=/home/thomas/workspace -v /var/run/docker.sock:/var/run/docker.sock tstachl/devenv"
# the folder containing repos on mac
alias repos="cd /Users/tstachl/Workspace/personal/repos"
