#!/usr/bin/env bash

sudo apt-get update -y \
  && sudo apt-get upgrade -y \
  && sudo apt-get install -y git zsh vim tmux curl gpg \
  && sudo chsh -s /usr/bin/zsh $USER \
  && sudo curl -fLo /usr/local/bin/yadm \
    https://github.com/TheLocehiliosan/yadm/raw/master/yadm \
  && sudo chmod a+x /usr/local/bin/yadm \
  && yadm clone --bootstrap https://github.com/tstachl/dotfiles.git

